### ISSUE TITLE
Issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by arubino** [marcoancona/MineTime#10]
I get the following error when launching Mine Time on Ubuntu 14.04 LTS

> A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.d2kYKb)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/keytar/lib/keytar.js:55:3)

any suggestion?

**Comment by marcoancona** [comment]
This might be due to the fact we compiled on Ubuntu 16.04. While we look into the problem, you could try to update your libstdc++ as explained here: https://stackoverflow.com/a/16605759/3038460

**Comment by maraghuram** [comment]
Did this work?

**Comment by arubino** [comment]
no, unfortunatelly that did not work.

**Comment by marcoancona** [comment]
Are you running 32 or 64 bits?

**Comment by arubino** [comment]
64

**Comment by maraghuram** [comment]
Same here. Running 64-bit Ubuntu 14.04 and libstdc++ is up-to-date, but Mine Time crashes with same error.

**Comment by marcoancona** [comment]
We just release version 1.0.11 that should solve this problem of compatibility with 14.04 LTS. 
You can download it here: https://github.com/marcoancona/MineTime/releases
You feedback with this new version would be much appreciated.

**Comment by arubino** [comment]
Working with my 14.04 LTS. Many thanks!

**Comment by marcoancona** [comment]
You are welcome.

**Comment by maraghuram** [comment]
Yep, working now. Thanks for the quick fix!

**Comment by neuromancer-ita** [comment]
Back in town with new version, at least 1.1.1 and 1.1.2
:(
Same errors as before 

```
info:    Main process: 21659
info:    Frameworks: {"http_parser":"2.7.0","node":"8.2.1","v8":"5.9.211.38","uv":"1.13.1","zlib":"1.2.11","ares":"1.10.1-DEV","modules":"57","openssl":"1.0.2l","electron":"1.8.1","chrome":"59.0.3071.115","atom-shell":"1.8.1"}
info:    Log file path: /home/stefano/.config/MineTime/logs/log.log
info:     uuid=21ac0109-e759-4cc2-b8b8-8a393a11355b
error:    Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.TXiT5h)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/keytar/lib/keytar.js:61:3)
```

**Comment by marcoancona** [comment]
Just release 1.1.3 that fixes this. Sorry for the inconvenience.
