### ISSUE TITLE
Not able to connect to CalDAV if e-mail is part of the link

### ISSUE THREAD

**Issue by balazsdukai** [marcoancona/MineTime#124]
I'm trying to connect to a CalDAV server. See the link below (replaced my e-mail). 
```
https://exchgw.tudelft.nl/users/<e.mail@tudelft.nl>/calendar
```
I believe the url parser doesn't handle when an e-mail part of the link since I get the traceback below when trying to connect.

```
warn: CalDAV account creation failed with message=Parameter "url" must be a string, not undefined, stack=TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at urlParse (url.js:97:13)
    at Url.resolve (url.js:654:29)
    at Object.urlResolve [as resolve] (url.js:650:40)
    at callee$0$0$ (/opt/MineTime/resources/app.asar/node_modules/dav/build/accounts.js:136:62)
    at tryCatch (/opt/MineTime/resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/opt/MineTime/resources/app.asar/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/opt/MineTime/resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21)
    at onFulfilled (/opt/MineTime/resources/app.asar/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
warn: CalDAV account creation failed with message=Bad status 503: Invalid Caldav request: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0], stack=Error: Bad status 503: Invalid Caldav request: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
    at Request._callback (/opt/MineTime/resources/app.asar/node_modules/dav/build/XMLHttpRequestWrapper.js:84:20)
    at Request.self.callback (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9), code=503
```

If I only use `https://exchgw.tudelft.nl/users` (which is not valid), then i get):

```
warn: CalDAV account creation failed with message=Bad status 404: Folder '/users' not found, stack=Error: Bad status 404: Folder '/users' not found
    at Request._callback (/opt/MineTime/resources/app.asar/node_modules/dav/build/XMLHttpRequestWrapper.js:84:20)
    at Request.self.callback (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9), code=404
warn: CalDAV account creation failed with message=Bad status 503: Invalid Caldav request: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0], stack=Error: Bad status 503: Invalid Caldav request: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
    at Request._callback (/opt/MineTime/resources/app.asar/node_modules/dav/build/XMLHttpRequestWrapper.js:84:20)
    at Request.self.callback (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9), code=503
```

**Comment by balazsdukai** [comment]
I just tried with MineTime 1.6.2, still the same issue

**Comment by marcoancona** [comment]
We have implemented several fixes to CalDAV in the meanwhile. If the problem persists, please contact us https://minetime.ai/#contact
