### ISSUE TITLE
No events are saved using the latest MineTime 1.6.0 on Linux

### ISSUE THREAD

**Issue by logix2** [marcoancona/MineTime#135]
Using MineTime 1.6.0 on Linux (Ubuntu 19.04), I can't add calendar (using Google Calendar) events as they are not saved, so they disappear after clicking the "Save" button. Also, sometimes when I try to add an event, the "Save" button doesn't even appear.

Console log:

```
$ minetime 

info: Main process: 21710
info: Frameworks: {"node":"12.0.0","v8":"7.3.492.27-electron.0","uv":"1.27.0","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"70","nghttp2":"1.34.0","napi":"4","llhttp":"1.1.1","http_parser":"2.8.0","openssl":"1.1.0","icu":"63.1","unicode":"11.0","electron":"5.0.10","chrome":"73.0.3683.121"}
[Timing] App ready in 200.87671099975705 milliseconds.
Settings storage path: /home/logix/.config/MineTime/config.json
info: Log file path: /home/logix/.config/MineTime/logs/log.log
info: Backend: loading user...
2019-09-02T20:39:27.363+0300 I CONTROL  [initandlisten] MongoDB starting : pid=21784 port=50227 dbpath=/home/logix/.config/MineTime/calendars 64-bit host=logix-desktop
2019-09-02T20:39:27.363+0300 I CONTROL  [initandlisten] db version v3.2.10
2019-09-02T20:39:27.363+0300 I CONTROL  [initandlisten] git version: 79d9b3ab5ce20f51c272b4411202710a082d0317
2019-09-02T20:39:27.364+0300 I CONTROL  [initandlisten] allocator: tcmalloc
2019-09-02T20:39:27.364+0300 I CONTROL  [initandlisten] modules: none
2019-09-02T20:39:27.364+0300 I CONTROL  [initandlisten] build environment:
2019-09-02T20:39:27.364+0300 I CONTROL  [initandlisten]     distarch: x86_64
2019-09-02T20:39:27.364+0300 I CONTROL  [initandlisten]     target_arch: x86_64
2019-09-02T20:39:27.364+0300 I CONTROL  [initandlisten] options: { config: "/opt/MineTime/resources/app.asar.unpacked/bin/mongo/mongod.conf", net: { bindIp: "127.0.0.1", port: 50227 }, security: { authorization: "enabled" }, storage: { dbPath: "/home/logix/.config/MineTime/calendars" } }
2019-09-02T20:39:27.387+0300 I -        [initandlisten] Detected data files in /home/logix/.config/MineTime/calendars created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-09-02T20:39:27.387+0300 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=8G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2019-09-02T20:39:27.621+0300 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/home/logix/.config/MineTime/calendars/diagnostic.data'
2019-09-02T20:39:27.621+0300 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
2019-09-02T20:39:27.621+0300 I NETWORK  [initandlisten] waiting for connections on port 50227
2019-09-02T20:39:27.898+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40574 #1 (1 connection now open)
Creating a user without roles is deprecated in MongoDB >= 2.6
2019-09-02T20:39:27.907+0300 I ACCESS   [conn1] Unauthorized: not authorized on admin to execute command { createUser: "admin", customData: {}, roles: [ "root" ], digestPassword: false, pwd: "xxx" }
Admin.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
2019-09-02T20:39:27.921+0300 I ACCESS   [conn1] Successfully authenticated as principal admin on admin
[Timing] Mongo ready in 2378.068355999887 milliseconds.
2019-09-02T20:39:27.944+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40576 #2 (2 connections now open)
2019-09-02T20:39:27.948+0300 I ACCESS   [conn2] Successfully authenticated as principal admin on admin
2019-09-02T20:39:27.966+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40578 #3 (3 connections now open)
2019-09-02T20:39:27.977+0300 I ACCESS   [conn3] Successfully authenticated as principal admin on admin
2019-09-02T20:39:27.992+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40580 #4 (4 connections now open)
2019-09-02T20:39:27.998+0300 I ACCESS   [conn4] Successfully authenticated as principal admin on admin
2019-09-02T20:39:27.999+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40582 #5 (5 connections now open)
2019-09-02T20:39:28.007+0300 I ACCESS   [conn5] Successfully authenticated as principal admin on admin
error: Error on sync of calendar 5ba0e77395a0bf4db6112a5b. Next trial in in 30 secs... invalid_grant
error: Error on sync of calendar 5ba0e77395a0bf4db6112a5d. Next trial in in 30 secs... invalid_grant
error: Error on sync of calendar 5ba0e77395a0bf4db6112a5c. Next trial in in 30 secs... invalid_grant
2019-09-02T20:39:29.589+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40630 #6 (6 connections now open)
2019-09-02T20:39:29.590+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:40632 #7 (7 connections now open)
2019-09-02T20:39:29.597+0300 I ACCESS   [conn7] Successfully authenticated as principal admin on admin
[Timing] Window ready to show in 5130.511599000543 milliseconds.
error: UncaughtException message=mainWindow.getMimimumSize is not a function, stack=TypeError: mainWindow.getMimimumSize is not a function
    at /opt/MineTime/resources/app.asar/dist/main/main.js:1:15474
    at callSubscriberWithDelayedExceptions (/opt/MineTime/resources/app.asar/node_modules/pubsub-js/src/pubsub.js:54:4)
    at deliverMessage (/opt/MineTime/resources/app.asar/node_modules/pubsub-js/src/pubsub.js:75:5)
    at Timeout.deliverNamespaced [as _onTimeout] (/opt/MineTime/resources/app.asar/node_modules/pubsub-js/src/pubsub.js:86:4)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
(node:21710) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at /opt/MineTime/resources/app.asar/dist/main/connectors/calendars/google/google.js:1:2491
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:21710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:21710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: Error on sync of calendar 5ba0e77395a0bf4db6112a5b. Next trial in in 30 secs... invalid_grant
error: Error on sync of calendar 5ba0e77395a0bf4db6112a5c. Next trial in in 30 secs... invalid_grant
error: Error on sync of calendar 5ba0e77395a0bf4db6112a5d. Next trial in in 30 secs... invalid_grant
```
I have upgraded from an older MineTime version (don't remember from which version), and I haven't used MineTime in a while, but it used to work.

Maybe I need to re-authenticate MineTime with my Google account? This was my first thought, but I can't seem to find a button to remove an existing account and re-authenticate.

**Comment by logix2** [comment]
I managed to find how to delete my Google account, re-authenticated and it worked now, so I'm closing this bug. But maybe the app should show some kind of feedback in such cases...

**Comment by marcoancona** [comment]
Thanks for reporting. Please let me know if the problem reappears.
