### ISSUE TITLE
Minetime window do not show up and can't be killed

### ISSUE THREAD

**Issue by flg** [marcoancona/MineTime#159]
Version 1.7.2 (for Linux)

Minetime seems to be running:
```bash
$ ps -ef | grep minetime
flg   3181  3165  0 11:35 ?        00:00:00 /opt/MineTime/minetime --type=zygote
flg   3193  3181  0 11:35 ?        00:00:00 /opt/MineTime/minetime --type=zygote
flg   3572  3165  0 11:35 ?        00:00:00 /opt/MineTime/minetime --type=gpu-process --field-trial-handle=256361433411953221,16373792889350447313,131072 --disable-features=SpareRendererForSitePerProcess --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --service-request-channel-token=8516683537791841487
flg   3601  3572  0 11:35 ?        00:00:00 /opt/MineTime/minetime --type=broker
flg   3627  3165  0 11:35 ?        00:00:00 /opt/MineTime/minetime --type=utility --field-trial-handle=256361433411953221,16373792889350447313,131072 --disable-features=SpareRendererForSitePerProcess --lang=en-GB --service-sandbox-type=network --service-request-channel-token=15770823949894779212 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```

But I don't see the window and I didn't see the splashscreen at startup.

It can't be entirely killed (thus restarted), some processes are just respawned (notice the new PIDs):
```bash
$ killall -9 minetime
$ ps -ef | grep minetime
flg   4705  3165  2 11:42 ?        00:00:00 /opt/MineTime/minetime --type=gpu-process --field-trial-handle=256361433411953221,16373792889350447313,131072 --disable-features=SpareRendererForSitePerProcess --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --service-request-channel-token=4440460827910310335
flg   4706  3165  1 11:42 ?        00:00:00 /opt/MineTime/minetime --type=utility --field-trial-handle=256361433411953221,16373792889350447313,131072 --disable-features=SpareRendererForSitePerProcess --lang=en-GB --service-sandbox-type=network --service-request-channel-token=17426364222622264393 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
flg   4716  4705  0 11:42 ?        00:00:00 /opt/MineTime/minetime --type=broker
```

Not sure what to do from here. Any logs? Any useful information I can provide you with?

**Comment by flg** [comment]
Managed to start it from the command line.

```
info: Main process: 4088
info: Frameworks: {"node":"12.8.1","v8":"7.8.279.23-electron.0","uv":"1.30.1","zlib":"1.2.11","brotli":"1.0.7","ares":"1.15.0","modules":"75","nghttp2":"1.39.2","napi":"4","llhttp":"1.1.4","http_parser":"2.8.0","openssl":"1.1.0","icu":"64.2","unicode":"12.1","electron":"7.1.1","chrome":"78.0.3904.99"}
[Timing] App ready in 375.15492800000357 milliseconds.
Settings storage path: /home/flegoff/.config/MineTime/config.json
info: Log file path: /home/flegoff/.config/MineTime/logs/log.log
error: UncaughtException message=/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/MineTime/resources/app.asar.unpacked/node_modules/keytar/build/Release/keytar.node), stack=Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/MineTime/resources/app.asar.unpacked/node_modules/keytar/build/Release/keytar.node)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```

Same problem with version 1.7.1 and 1.7.2, RPMs and AppImages.

Version 1.7.0 seems to work fine, though there is this message in the console:
```
[Scheduling service] [5441] Failed to execute script main

[Scheduling service] Traceback (most recent call last):
  File "src/main.py", line 13, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "src/scheduler/Scheduler.py", line 13, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "src/preprocessing/baselines/data_preprocessor.py", line 5, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "datamodel/cal/event.py", line 11, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "datamodel/cal/vocabulary.py", line 8, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "spacy/__init__.py", line 10, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "thinc/neural/__init__.py", line 4, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "thinc/neural/_classes/model.py", line 7, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "srsly/__init__.py", line 4, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "srsly/_json_api.py", line 8, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "srsly/ujson/__init__.py", line 1, in <module>
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEIOwFn8m/libstdc++.so.6)

error: [Scheduling service] exit 255
```

**Comment by flg** [comment]
Since it seems related to an issue with the standard C++ library, my OS is CentOS 7 and libstdc++'s version is 4.8.5.

**Comment by marcoancona** [comment]
Did you update to 1.7.2 from an older version or was this a fresh install?

**Comment by flg** [comment]
Updated first. Then uninstalled everything and reinstalled. Then tried with AppImages.

**Comment by marcoancona** [comment]
The just-released 1.7.3 avoids loading `keytar` on Linux, which should solve the crash occurring with 1.7.2.

**Comment by flg** [comment]
Version 1.7.3 seems to work indeed. Thanks for adressing the issue.

You'll find attached the standard output and error as the messages I reported above are still here.

[minetime173.err.txt](https://github.com/marcoancona/MineTime/files/3932303/minetime173.err.txt)
[minetime173.out.txt](https://github.com/marcoancona/MineTime/files/3932304/minetime173.out.txt)

A message says: "Using keytar:  true"

And the zoom is not working. CTRL + and CTRL - have no effect.

Let me know if you want more information/testing.

Feel free to close the ticket if you don't want to tollow up on these additional comments.

**Comment by marcoancona** [comment]
Does the zoom work if you use the topbar menu (View -> Zoom In/Out)?

**Comment by flg** [comment]
Yes it does.

And the same kestrokes (ctrl+ and ctrl-) work fine for the zoom in Firefox for example.

**Comment by marcoancona** [comment]
> 
> A message says: "Using keytar: true"
> 


Related to https://github.com/marcoancona/MineTime/issues/164
