### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by pchampio** [marcoancona/MineTime#168]
I've seen proxy errors on this tracker.
If I understand correctly, it's not a MineTime error, but a error in the dependency used. I'm I understanding correctly ?

Here is the output of Minetime (I did set the all of XXX_PROXY venv according to my network)
```log
error: [Scheduling service] exit 255
Net error - proxy.univ-ZZZZZZ.fr - write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

error: Backend error write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

[Timing] Window ready to show in 3320.928529000026 milliseconds.
(electron) 'setZoomFactor function' is deprecated and will be removed. Please use 'zoomFactor property' instead.
Net error - radicale.YYYYY.com - socket hang up
Net error - zimbra.XXXXX.fr - socket hang up
Net error - radicale.YYYYY.com - socket hang up
Net error - radicale.YYYYY.com - socket hang up
error: CalDAV: error while running runAsync -  message=ETIMEDOUT, stack=Error: ETIMEDOUT
    at Timeout._onTimeout (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7), code=ETIMEDOUT, connect=true
error: Error on sync of calendar 5db83002f06e51024e306a66. Next trial in in 30 secs... message=ETIMEDOUT, stack=Error: ETIMEDOUT
    at Timeout._onTimeout (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7), code=ETIMEDOUT, connect=true
error: CalDAV: error while running runAsync -  message=ETIMEDOUT, stack=Error: ETIMEDOUT
    at Timeout._onTimeout (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7), code=ETIMEDOUT, connect=true
error: Error on sync of calendar 5dd7ab4d72a310070a5fdf0e. Next trial in in 30 secs... message=ETIMEDOUT, stack=Error: ETIMEDOUT
    at Timeout._onTimeout (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7), code=ETIMEDOUT, connect=true
error: CalDAV: error while running runAsync -  message=ETIMEDOUT, stack=Error: ETIMEDOUT
    at Timeout._onTimeout (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7), code=ETIMEDOUT, connect=true
error: Error on sync of calendar 5db83002f06e51024e306a68. Next trial in in 30 secs... message=ETIMEDOUT, stack=Error: ETIMEDOUT
    at Timeout._onTimeout (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7), code=ETIMEDOUT, connect=true
error: CalDAV: error while running runAsync -  message=ETIMEDOUT, stack=Error: ETIMEDOUT
    at Timeout._onTimeout (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7), code=ETIMEDOUT, connect=true
error: Error on sync of calendar 5db83002f06e51024e306a67. Next trial in in 30 secs... message=ETIMEDOUT, stack=Error: ETIMEDOUT
    at Timeout._onTimeout (/opt/MineTime/resources/app.asar/node_modules/dav/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7), code=ETIMEDOUT, connect=true
Net error - radicale.YYYYY.com - socket hang up
Net error - radicale.YYYYY.com - socket hang up
Net error - zimbra.XXXXX.fr - socket hang up
Net error - radicale.YYYYY.com - socket hang up
Net error - proxy.univ-ZZZZZZ.fr - write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

error: [Logger] Error: write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

Net error - proxy.univ-ZZZZZZ.fr - write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

error: [Logger] Error: write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

Net error - proxy.univ-ZZZZZZ.fr - write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

error: [Logger] Error: write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

Net error - proxy.univ-ZZZZZZ.fr - write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

error: [Logger] Error: write EPROTO 42364214780360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:
```

**Comment by pchampio** [comment]
Note, the proxy isn't secured.
-> `ALL_PROXY="http://proxy.univ-ZZZZZZ.fr:8989"`
It's the same address for `HTTPS_PROXY` and `HTTP_PROXY`.
