### ISSUE TITLE
Can't add calendars on KDE neon

### ISSUE THREAD

**Issue by BRM95** [marcoancona/MineTime#170]
MineTiime gets stuck on authorization for account. The account itself gives privileges to MineTime but MineTime itself fails with Unable to authorize error. The output of the log file is given below. 

Both keyring and seahorse are installed. I've also tried purging and reinstalling MineTime (deleted the MineTime folder in .config as well) with the same outcome. I'm using the .deb package provided on the site. The issue persists for Outlook accounts as well.

![image](https://user-images.githubusercontent.com/22768325/73607130-a6040d00-45b2-11ea-88c5-2097293676ec.png)

![image](https://user-images.githubusercontent.com/22768325/73607121-8967d500-45b2-11ea-8a77-8fceb91373e8.png)

2020-02-01T20:18:03.088Z - info:  
2020-02-01T20:18:03.089Z - info: *********************
2020-02-01T20:18:03.089Z - info: App ready
2020-02-01T20:18:03.089Z - info:  0=/opt/MineTime/minetime
2020-02-01T20:18:03.089Z - info: *********************

2020-02-01T20:18:03.134Z - info: Waiting for open db connection on port 50227
2020-02-01T20:18:03.134Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:03.145Z - warn: APPIMAGE env is not defined, current application is not an AppImage
2020-02-01T20:18:03.145Z - warn: APPIMAGE env is not defined, current application is not an AppImage
2020-02-01T20:18:03.146Z - warn: Updater:  message=autoUpdater reported inactive, stack=Error: autoUpdater reported inactive
    at e.<anonymous> (/opt/MineTime/resources/app.asar/dist/main/updater.js:1:4148)
    at tryCatch (/opt/MineTime/resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/opt/MineTime/resources/app.asar/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/opt/MineTime/resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/opt/MineTime/resources/app.asar/dist/main/updater.js:1:71)
    at i (/opt/MineTime/resources/app.asar/dist/main/updater.js:1:289)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
2020-02-01T20:18:03.146Z - info: Updater: manual check on https://api.github.com/repos/marcoancona/MineTime/releases/latest
2020-02-01T20:18:03.511Z - info: Updater: found latest v=v1.7.4, prerelease=false
2020-02-01T20:18:03.512Z - info: Updater: comparing with current v=1.7.4
2020-02-01T20:18:03.650Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:04.154Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:04.657Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.159Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.273Z - info: Waiting for open db connection on port 50227
2020-02-01T20:18:05.273Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.340Z - info: Waiting for open db connection on port 50227
2020-02-01T20:18:05.341Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.356Z - info: Waiting for open db connection on port 50227
2020-02-01T20:18:05.356Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.538Z - info: Waiting for open db connection on port 50227
2020-02-01T20:18:05.538Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.660Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.760Z - info: Waiting for open db connection on port 50227
2020-02-01T20:18:05.760Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.776Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.842Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:05.858Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:06.040Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:06.161Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:06.262Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:06.277Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:06.344Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:06.360Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]
2020-02-01T20:18:06.542Z - info: Connecting [mongodb://127.0.0.1:50227/minetime]

**Comment by marcoancona** [comment]
It looks like inter-process communication via 127.0.0.1 is not working... do you have any particular network of firewall configuration?

**Comment by BRM95** [comment]
I checked and I hadn't configured any firewall. I'll check again once I get home

**Comment by BRM95** [comment]
No, no firewall is enabled.
