### ISSUE TITLE
Scheduling service exits with 255 during startup

### ISSUE THREAD

**Issue by FriesischScott** [marcoancona/MineTime#171]
I am running MineTime 1.7.4 from the AppImage on Solus. During startup the following error is reported:

```zsh
[Scheduling service] [5272] Failed to execute script main
Traceback (most recent call last):
  File "socketio/tornado.py", line 4, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "engineio/async_drivers/tornado.py", line 6, in <module>
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/main.py", line 6, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "socketio/__init__.py", line 12, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "socketio/tornado.py", line 7, in <module>
ModuleNotFoundError: No module named 'engineio.async_tornado'

error: [Scheduling service] exit 255
```

**Comment by marcoancona** [comment]
This is now fixed.
