### ISSUE TITLE
Mine Time is offline please check your connectivity

### ISSUE THREAD

**Issue by davigega** [marcoancona/MineTime#173]
Hello,

I'm using MineTime since a couple of Months by now and I love it. I installed it on a Gnome 3.34.2 running on a Debian testing machine.

I launch MineTime as a default startup application and everything works perfectly. It seems that once I close and I relaunch it later during the day, MineTime is not able to reconnected to the internet, although the computer is.

"MineTime is offline. Please check your connectivity" is the message I receive.

Apparently this is due to the fact that when I close the GUI I'm not actually closing the application.
`~$ minetime`
`Second instance: terminating`

`~$ ps aux | grep MineTime`
shows in fact an instance of MineTime that I can `kill` manually. Killing the application and relaunching it helps getting the connection back.

Another element that might help is that once I fresh new start the application I get the following errors:

```
[Scheduling service] [8103] Failed to execute script main
Traceback (most recent call last):
  File "socketio/tornado.py", line 4, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "engineio/async_drivers/tornado.py", line 6, in <module>
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/main.py", line 6, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "socketio/__init__.py", line 12, in <module>
  File "/home/vsts/work/1/s/services/scheduling/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "socketio/tornado.py", line 7, in <module>
ModuleNotFoundError: No module named 'engineio.async_tornado'

error: [Scheduling service] exit 255
```
Although both `socketio` and `engineio` are both installed.
The application runs flawless anyway.

Thank you for your time

**Comment by marcoancona** [comment]
Thanks for reporting these issues. The problem of connectivity should not be related to the fact that the application does not completely terminate. There is a connectivity check running every 10 seconds and this should not be affected by multiple instances being active at the same time.
