### ISSUE TITLE
Lots of "Could not find collection on remote" errors

### ISSUE THREAD

**Issue by skalarproduktraum** [marcoancona/MineTime#179]
I just realised that the logfile of Minetime is full of errors like

```
2020-03-17T05:34:22.839Z - error: CalDAV: error while running syncCalendar -  message=Could not find collection on remote. Was it deleted?, stack=Error: Could not find collection on remote. Was it deleted?
    at Object.callee$0$0$ (C:\...\AppData\Local\Programs\MineTime\resources\app.asar\node_modules\dav\build\webdav.js:141:15)
    at tryCatch (C:\...\AppData\Local\Programs\MineTime\resources\app.asar\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\...\AppData\Local\Programs\MineTime\resources\app.asar\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (C:\...\AppData\Local\Programs\MineTime\resources\app.asar\node_modules\regenerator-runtime\runtime.js:114:21)
    at onFulfilled (C:\...\AppData\Local\Programs\MineTime\resources\app.asar\node_modules\co\index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

The calendars however show up and seem to be in sync.

**Comment by marcoancona** [comment]
This should be fixed in 1.8.4+. If the problem persists, feel free to leave a comment here.
