### ISSUE TITLE
Exchange account requires constant relink

### ISSUE THREAD

**Issue by balazsdukai** [marcoancona/MineTime#229]
I have an Exchange account set up and in general it works well. However every now and then, like multiple times a day, it breaks. I'm not able to pinpoint exactly when this happens, but it does not seem to be related to exiting/starting MineTime, because during the day I just have have it running all the time.

When I start from the console I get this log:

```
2020-09-09T14:23:17.348+0200 I ACCESS   [conn5] Successfully authenticated as principal admin on admin
error: Stopping EWS sync due to error message=Abort sync of EWS account 5f47be2426231329f5a7d52d cause relink is required, stack=Error: Abort sync of EWS account 5f47be2426231329f5a7d52d cause relink is required
    at /opt/MineTime/resources/app.asar/dist/main/connectors/calendars/ews/ews.js:1:31329
    at tryCatch (/opt/MineTime/resources/app.asar/node_modules/dav/dav.js:27264:40)
    at Generator.invoke [as _invoke] (/opt/MineTime/resources/app.asar/node_modules/dav/dav.js:27494:22)
    at Generator.next (/opt/MineTime/resources/app.asar/node_modules/dav/dav.js:27319:21)
    at d (/opt/MineTime/resources/app.asar/dist/main/connectors/calendars/ews/ews.js:1:760)
    at o (/opt/MineTime/resources/app.asar/dist/main/connectors/calendars/ews/ews.js:1:963)
    at /opt/MineTime/resources/app.asar/dist/main/connectors/calendars/ews/ews.js:1:1022
    at new Promise (<anonymous>)
    at /opt/MineTime/resources/app.asar/dist/main/connectors/calendars/ews/ews.js:1:903
    at /opt/MineTime/resources/app.asar/dist/main/connectors/calendars/ews/ews.js:1:32601
    at /opt/MineTime/resources/app.asar/dist/main/models/account.js:1:7769
    at handleCallback (/opt/MineTime/resources/app.asar/node_modules/mongodb/lib/utils.js:120:56)
    at /opt/MineTime/resources/app.asar/node_modules/mongodb/lib/collection.js:1416:5
    at handleCallback (/opt/MineTime/resources/app.asar/node_modules/mongodb/lib/utils.js:120:56)
    at /opt/MineTime/resources/app.asar/node_modules/mongodb/lib/cursor.js:683:5
    at handleCallback (/opt/MineTime/resources/app.asar/node_modules/mongodb-core/lib/cursor.js:171:5)
    at nextFunction (/opt/MineTime/resources/app.asar/node_modules/mongodb-core/lib/cursor.js:691:5)
    at /opt/MineTime/resources/app.asar/node_modules/mongodb-core/lib/cursor.js:602:7
    at queryCallback (/opt/MineTime/resources/app.asar/node_modules/mongodb-core/lib/cursor.js:232:18)
    at /opt/MineTime/resources/app.asar/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

I contacted the sysadmin and they say that my user gets blocked by the system, because it appears that I have too many invalid tries for my password.

I attached the full console output [minetime.log](https://github.com/marcoancona/MineTime/files/5195101/minetime.log)

I on kubuntu 18.04 and installed app from the deb package. Using MineTime 1.8.6

**Comment by balazsdukai** [comment]
It seems that this was a false alarm and the issue was somewhere else, sorry.
