### ISSUE TITLE
libgnome-keyring.so.0 dependency prevents from launching

### ISSUE THREAD

**Issue by probonopd** [marcoancona/MineTime#7]
libgnome-keyring.so.0 is missing in the AppImage, hence it does not run on my KDE openSUSE LEAP 42.2 system:

```
linux@linux:/isofrom/boot/iso> /home/linux/Downloads/MineTime-1.0.9-x86_64.AppImage 
6772
[LOG] app.firststart
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/.mount_EPi8JS/usr/bin/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/tmp/.mount_EPi8JS/usr/bin/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4)
```

Please remove the dependency on libgnome-keyring.so.0 or bundle it inside the AppImage.

**Comment by marcoancona** [comment]
The new version of `node-keytar` uses `libsecret` instead of `gnome-keyring`. This should increase portability without increasing the package size.

**Comment by marcoancona** [comment]
Of course this assumes `libsecret` is preinstalled in the target system, which I am not so sure about...

**Comment by marcoancona** [comment]
MineTime 1.0.10 released! Feel free to re-open if the problem persists on any distros.
